coolmankid12345/stalker-14-EN

Resources/Prototypes/_Stalker/GameRules/events.yml

Changed emission damages and added a weight component.

(Hopefully) Better emissions

---

Resources/Prototypes/_Stalker/ShopPresets/factionsTorgomats/merc.yml

Add merc revolver to merc vend

---

Resources/Prototypes/_Stalker/Roles/Jobs/mercenaries.yml
Resources/Prototypes/_Stalker/ai_factions.yml

Made the Hostile npc faction non-hostile to Mercs. Why? So Dottie doesn't ragequit and because holy shit it's annoying getting our base getting camped by them.

Learn to love your neighbour 

---

Resources/Prototypes/_Stalker/ShopPresets/Research_Institutes.yml
Resources/Prototypes/_Stalker/ShopPresets/factionsTorgomats/merc.yml
Resources/Prototypes/_Stalker/ShopPresets/factionsTorgomats/military.yml

Added some more western guns to merc vend, sandbags and barbed wire to mili vend, and medical belts to sci vend.

More stock for Mercs, Mili, and Sci

---

Resources/Prototypes/_Stalker/ShopPresets/NikitaAlkash.yml

Weed grinding

---

Resources/Maps/_ST/World/UndergroundWildsBar100radsV34.yml
Resources/Prototypes/_Stalker/ScriptedEntities/Portals/mapLoader.yml

*Added Warp Points to Red Forest and deleted 6 anom spawners that were legit 1 tile away from the main road teleport to avoid teleport camping and rage quits (You can thank me later)
*Added Warp Point to Bar and changed radio so everyone's sanity is saved.
*Fixed Undeground file to say Underground and fixed it in the maploader as well (Yes I tested to make sure it worked...)

Map Edits and Resolved File Typo

---

Resources/Prototypes/_Stalker/Entities/Objects/Clothing/Head/T2/TinfoilHat.yml

It now has intended psy resistance.

Fixed the tin foil hat

---

Resources/Prototypes/_Stalker/GameRules/events.yml

Made emissions more scary, increased damage per tick from 2 to 5

Makes emissions actually scary..

---

Resources/Locale/en-US/_stalker/job/department.ftl
Resources/Locale/en-US/_stalker/markings/human.ftl
Resources/Locale/en-US/_stalker/roles/jobs.ftl
Resources/Prototypes/_Stalker/Roles/Jobs/Evolvers/evolver.yml
Resources/Prototypes/_Stalker/Roles/Jobs/Evolvers/pack.yml
Resources/Prototypes/_Stalker/Roles/Jobs/Evolvers/symbiote.yml

cleaned up some locale strings i missed, cleaned up job locale strings while i was here

locale string stuff

---

Resources/Prototypes/_Stalker/Roles/Jobs/bands.yml
Resources/Prototypes/_Stalker/Roles/Jobs/dolg.yml
Resources/Prototypes/_Stalker/Roles/Jobs/freedom.yml
Resources/Prototypes/_Stalker/Roles/Jobs/mercenaries.yml
Resources/Prototypes/_Stalker/Roles/Jobs/militaries.yml
Resources/Prototypes/_Stalker/Roles/Jobs/sci.yml

Added teeth to some roles that should've had them but didn't, and made it so heads can actually use their faction points/manage members.

Faction heads able to manage members/points

---

Resources/Prototypes/_Stalker/ShopPresets/factionsTorgomats/dolg.yml

Added ash-12, svu, the mags for both, ash 12 ammo T2, and T4 ammo. Old PR explains more but its essentially for buffing duty due to balancing coming from the russian server, where they use artifacts as Duty.

Small Duty Buff

---

Resources/Prototypes/_Stalker/ShopPresets/Barmen.yml
Resources/Prototypes/_Stalker/ShopPresets/OUTDATED/clearsky.yml
Resources/Prototypes/_Stalker/ShopPresets/OUTDATED/merc.yml
Resources/Prototypes/_Stalker/ShopPresets/OUTDATED/military.yml
Resources/Prototypes/_Stalker/ShopPresets/OUTDATED/renegats.yml
Resources/Prototypes/_Stalker/ShopPresets/factionsTorgomats/Research_Institutes.yml

Clear sky has been given a 1.3x sell rate so they're a viable alternative to Eco's 1.5x, the also got given 8.5mm buckshot.
Ecologists have been given their SSP suits back along with the bear detector. The cost of scientific equipment was also lowered to its original cost of 500 instead of 1000, they also now have access to flechette shells to better deal with mutants.
Military has received major Government funding. They now have access to a larger variety of armaments at incredibly low cost. 
Mercenaries now have access to a vast array of western firearms.
Renegades can get the full "I drive" experience.
Barman also has gunpowder again.

Faction vendor updates

---

Resources/Prototypes/_Stalker/Entities/Structures/Shops/clearsky.yml
Resources/Prototypes/_Stalker/Entities/Structures/Shops/renegates.yml

What this PR does is reverts russian PR that changed clear skies and renegades shop completely. 
:cl:
tweak: Clear Skies + Renegades Shop back to EN branch.
/:cl:

Clear Skies and Renegades Vendor Back to Normal

---

Content.Client/_CD/Engraving/EngraveableSystem.cs
Content.Server/_CD/Engraving/EngraveableSystem.cs
Content.Shared/_CD/Engraving/EngraveableComponent.cs
Content.Shared/_CD/Engraving/SharedEngraveableSystem.cs
Resources/Locale/en-US/_CD/engraving/engraving.ftl
Resources/Prototypes/_Stalker/Entities/Objects/Weapons/Guns/base.yml
Resources/Prototypes/_Stalker/Entities/Objects/Weapons/Melee/bats.yml
Resources/Prototypes/_Stalker/Entities/Objects/Weapons/Melee/hummers.yml
Resources/Prototypes/_Stalker/Entities/Objects/Weapons/Melee/knifes.yml

port of cosmatic-drift-14/cosmatic-drift#399 and cosmatic-drift-14/cosmatic-drift#529 as well as the minor locale changes i made in impstation/imp-station-14#1329
this adds an interact option to weapons to allow you to write a short message. i dont know how to test if this persists between rounds but i assume it does not and i don't think that's a concern
entirely for rp flavor

adds engraving to most (all?) weapons

---

Resources/Prototypes/_Stalker/Entities/Objects/Clothing/Belts/RPC.yml
Resources/Prototypes/_Stalker/Entities/Objects/Clothing/Cloak/Capes/T3.yml
Resources/Prototypes/_Stalker/Entities/Objects/Clothing/Head/T3/Sphere08.yml
Resources/Prototypes/_Stalker/Entities/Objects/Clothing/Legs/pants.yml
Resources/Prototypes/_Stalker/Entities/Objects/Clothing/OuterClothing/T1/Jacket.yml
Resources/Prototypes/_Stalker/Entities/Objects/Clothing/OuterClothing/T2/ArmorPlateVestLight.yml
Resources/Prototypes/_Stalker/Entities/Objects/Clothing/OuterClothing/T3/ArmorSeva.yml
Resources/Prototypes/_Stalker/Entities/Objects/Clothing/OuterClothing/T4/ArmorBerill5M.yml
Resources/Prototypes/_Stalker/Entities/Objects/Clothing/OuterClothing/T5/ArmorBulat.yml
Resources/Prototypes/_Stalker/Entities/Objects/Clothing/OuterClothing/T5/ArmorExoskeleton.yml
Resources/Prototypes/_Stalker/Entities/Objects/Clothing/OuterClothing/T5/ArmorPlateVestHeavy.yml
Resources/Prototypes/_Stalker/Entities/Objects/Clothing/Torso/turtlenecks.yml
Resources/Prototypes/_Stalker/Entities/Objects/Clothing/Uniforms/jumpsuits.yml

What this PR does is increases the radiation in all of monolith clothing and gear. This way this makes it where unless you are monolith you shouldn't BE wearing there gear. If you want to search monolith just press E on storage and it shouldnt kill you tldr. Basically this pr makes monolite not exist anymore.
:cl:
add: Radiation to all gear of monolith and increases it to the base gear.
/:cl:

Monolithilian Radiation

---

Resources/Maps/_ST/World/KordonPodzemV58.yml
Resources/Maps/_ST/World/MilitaryBase.yml
Resources/Maps/_ST/World/UndegroundWildsBar100radsV34.yml

Cordon - Warp Points, Rookie Village Trading Area
Red Forest - OKSOP Base fixes + MOAR LOOT!!
Garbage - Warp Points
Bar - Fixed Emission, Renamed for maploader, added thieving anoms to fuck over exploiters
Military Base - More RP items
Rostock - Removed Garbage Piles, Warp points
Cordon Underground - Removed Neutral Base, Fixed Militia Bar

Map Fixes / Tweaks

---

Resources/Locale/en-US/_stalker/interaction/interaction-popup-component.ftl
Resources/Prototypes/_Stalker/Entities/Mobs/Mutants/T1/flesh.yml

renegade buff

---

Resources/Prototypes/_Stalker/Entities/Objects/Tools/tools.yml

I figured out how to test it, and it works. :)
:cl:
add: Chainsaw engraving
/:cl:

Chainsaw Engrave

---

Resources/Locale/en-US/_stalker/entities/objects/weapons/guns/smgs/vz_61_skorpion.ftl

This change fixes the skorpion and readds skorpion in the name instead of scorpion. :sunglasses: This doesnt change the russian side of it, as I plan on doing an PR on there side fixing there file. 
:cl:
tweak: Skorpion
/:cl:

Skorpion Rename + Fix

---

Resources/Prototypes/_Stalker/Roles/Jobs/militaries.yml

Removes OKSLOP access to Military Officers; Due to Military Stalkers active
Adds Officer access to Military Stalker Commander for Officer Doors for CO/XO doors

Access Changes

---

Resources/Prototypes/Entities/Objects/Weapons/Melee/knife.yml
Resources/Prototypes/_Stalker/_Events/Entities/Objects/Weapons/Melee/chainsaw.yml

dog what the fuck is going on with these test fails
kukris and chainsaws get engraveable

kukris and chainsaws get engraveable

---

Resources/Prototypes/_Stalker/ShopPresets/Barmen.yml

Added M80 and a 20 round mag for the FN FAL at the bar.

Adding 762x51 mag and ammo to barman

---

Resources/Prototypes/_Stalker/Entities/Objects/Weapons/Guns/Snipers/vss.yml

VSS used to not have an accuracy component, it would miss like every shot. That is now fixed

Patched the VSS to actually be usable

---

Resources/Locale/en-US/_stalker/entities/objects/weapons/guns/smgs/vz_61_skorpion.ftl

This PR changes the 61 to an 82 in naming wise. As the Skorpion 82, uses 9x18. Awhile 61 uses .32 ACP. Which does not exist in the server and that would be bullet bloat if it is. 🤡 
:cl:
tweak: name of Skorpion to 82.
/:cl:

Skorpion Typo

---

Resources/Prototypes/_Stalker/Entities/Objects/Weapons/Guns/MachineGuns/RPD.yml

Slight RPD Nerf. Aimed to nerf RPD to be a burst fired LMG. Allowing you to suppress the enemy, but without 100% accuracy. Current RPD is TOO strong. Will need to nerf more later.

RPD Nerf - Minor

---

Resources/Maps/_ST/World/BolotaV27.yml
Resources/Maps/_ST/World/KordonPodzemV64.yml

Base Changes!

---

Resources/Locale/en-US/_stalker/roles/jobs.ftl

- Ecologists have proper locale strings
- supervisor locale strings no longer sound insane

job locale strings again

---

Resources/Locale/en-US/_stalker/entities/structures/shops/sci.ftl
Resources/Locale/en-US/_stalker/npc/_npc.ftl

Translated Mercenary dollar trader "Hummingbird"
Fixed the suffix on SciDollar trader so its easier to find in spawner

Shop Translations

---

Resources/Prototypes/Entities/Objects/Weapons/Melee/knife.yml
Resources/Prototypes/_Stalker/Entities/Objects/Artifact/thermal.yml
Resources/Prototypes/_Stalker/Entities/Objects/Consumable/medkits.yml
Resources/Prototypes/_Stalker/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/12x70.yml

- kukri looks like a kukri when its in a bag
- thermal artifacts now have a working pointlight
- tourniquet isnt invisible now
- magnum buckshot is ACTUALLY t2 now

fixing stuff

---

Resources/Maps/_ST/World/TemnajDolinaV74.yml
Resources/Maps/_ST/World/UndegroundWildsBar100radsV36.yml
Resources/Prototypes/_Stalker_EN/Entities/Objects/WarpPoints/warpPoints.yml

* Added Monolith Base TP
* Added Cordon Eco and Military TP
* Warp Points - Edited most map files to allow factions to TP to their bases and RV/Bar ,
* Garbage Sewers - Fixed portal
**INCASE ANYTHING IS WRONG ALL TELEPORTS ARE STILL MAPPED JUST BLOCKED OFF**

Map Teleport System

---

Resources/Maps/_ST/World/TemnajDolinaV74.yml
Resources/Maps/_ST/World/UndegroundWildsBar100radsV36.yml
Resources/Prototypes/_Stalker_EN/Entities/Objects/WarpPoints/warpPoints.yml

Reverts coolmankid12345/stalker-14-EN#122

Revert "Map Teleport System"

---

Resources/Prototypes/Entities/Objects/Specific/Medical/defib.yml
Resources/Prototypes/Entities/Objects/Specific/Medical/healing.yml
Resources/Prototypes/_Stalker/Entities/Objects/Consumable/medicine.yml
Resources/Prototypes/_Stalker/Entities/Objects/Consumable/medkits.yml
Resources/Prototypes/_Stalker/Entities/Objects/Storage/medkits.yml
Resources/Prototypes/_Stalker_EN/Entities/Objects/Consumable/Food/food.yml

* Gave medical items component for repo sorting
* Changed blood bag description to not break immersion! 
* Rotten fish meat now has trash comp
* Added Grizzly and CMS to the list

Trash and Repo
